TR-1-Gonza
facu-rodriguez/New-training-test pull request #2
Opened 2023-05-18 14:05 UTC by diazgonza17

## Summary

[Change!] Describe your feature, problems you had, notes, improvements and others.
Agregada nueva vista de Listado de Cuentas accesible desde HOME
Agregada funcionalidad que permite cambiar la cuenta actual al clickear una cuenta en el listado
## Test Cases

[Change!] Add test cases or useful information for reviewers to test and check pull request changes.

## Screenshots

[Change!] Show the screenshots of the views you modified.

## Jira Card

[Change!] Link to the associated Jira card.

2023-05-22 13:41 UTC, facu-rodriguez requested changes
Buen trabajo Gonza! Un par de cosas:

- Fijate que los datos queden alineados en todas las cards.

| Pr | Cambio pedido |
| :---: | :---: |
| ![Captura de pantalla de 2023-05-22 10-24-06](https://github.com/facu-rodriguez/New-training-test/assets/68086087/b03b9e79-643b-439e-82e9-4fa9590f2503) | ![Captura de pantalla de 2023-05-22 10-27-21](https://github.com/facu-rodriguez/New-training-test/assets/68086087/2abc850f-7191-4d43-ade5-583ae268d474) | 

--------------------------

El responsive debería verse bien:
 
![Captura de pantalla de 2023-05-22 10-34-02](https://github.com/facu-rodriguez/New-training-test/assets/68086087/52f65373-cf71-4fdd-b603-8ca4df8aa828)

-------------------------------------

En el hover de las cuentas cambiá el cursor!

2023-05-22 13:41 UTC, facu-rodriguez commented on src/app/screens/AccountsList/index.js
> +    <>
En vez de hacer esto usemos Fragment

2023-05-22 13:41 UTC, facu-rodriguez commented on src/app/screens/AccountsList/index.js
> +      <UTLabel classes={{ root: styles.title }}>Listado de cuentas</UTLabel>
Mové todos los textos al archivo de texts.js de cada utility!

2023-05-22 13:41 UTC, facu-rodriguez commented on src/app/screens/AccountsList/index.js
> +                  | {account.direccion}, {account.localidad}, {account.partido}
```suggestion
                  {`| ${account.direccion}, ${account.localidad}, ${account.partido}`}
```

2023-05-22 13:41 UTC, facu-rodriguez commented on src/app/screens/AccountsList/index.js
> +                <UTLabel>Relacion: {capitalize(account.relacion)}</UTLabel>
mover los textos!

2023-05-22 13:41 UTC, facu-rodriguez commented on src/app/screens/AccountsList/styles.module.scss
> +$gradient3-color: rgba(43, 191, 221, 1);
no deberíamos tener colores definidos acá, los colores los definimos dentro de la carpeta config, en cada utility, en el archivo de scss/colors.scss
Esto es así ya que cada cliente puede manejar distintos colores con las mismas variables, movete todo ahí!

2023-05-22 13:41 UTC, facu-rodriguez commented on src/app/screens/AccountsList/styles.module.scss
> +  text-align: center;
fijate el orden alfabético de las props! 

```suggestion
  font-size: #{$large};
  padding: 40px 20px 0;
  text-align: center;
  width: 100%;
```

2023-05-22 13:41 UTC, facu-rodriguez commented on src/app/screens/AccountsList/styles.module.scss
> +  width: 40%;
re ordená las props

2023-05-22 13:41 UTC, facu-rodriguez commented on src/app/screens/AccountsList/styles.module.scss
> +  font-size: #{$large};
```suggestion
  font-size: $large;
```

así deberías poder

2023-05-22 13:41 UTC, facu-rodriguez commented on src/app/screens/AccountsList/styles.module.scss
> +  font-size: #{$medium};
```suggestion
  font-size: $medium;
```

2023-05-22 13:41 UTC, facu-rodriguez commented on src/app/screens/Home/index.js
> +              </div>
Por qué agregaste un div nuevo? Podés mover el botón dentro del div de la línea 47, que ya wrapea al botón de historial de facturas.

Mové también el texto al archivo de texts

2023-05-22 13:44 UTC, facu-rodriguez requested changes
La cuenta seteada como la currentAccount no debería cambiar al ir a la vista de listado de cuenta:

https://github.com/facu-rodriguez/New-training-test/assets/68086087/395bb1c3-90db-44cd-94ab-8308fc124152

2023-05-22 13:44 UTC, facu-rodriguez commented on src/app/screens/AccountsList/index.js
> +    dispatch(AccountsActions.getAccounts());
no deberíamos llamarlo cada vez, ya recuperamos las cuentas previamente:

Uploading Peek 22-05-2023 10-42.mp4…

2023-05-22 14:43 UTC, diazgonza17 commented on src/app/screens/AccountsList/index.js
> +      <UTLabel classes={{ root: styles.title }}>Listado de cuentas</UTLabel>
Perfecto, corregido

2023-05-22 14:44 UTC, diazgonza17 commented on src/app/screens/AccountsList/index.js
> +                  | {account.direccion}, {account.localidad}, {account.partido}
Typo involuntario, eliminado

2023-05-22 14:46 UTC, diazgonza17 commented on src/app/screens/AccountsList/index.js
> +    <>
Perfecto, corregido

2023-05-22 15:22 UTC, diazgonza17 commented on src/app/screens/AccountsList/styles.module.scss
> +$gradient3-color: rgba(43, 191, 221, 1);
Excelente, corregido

2023-05-22 15:27 UTC, diazgonza17 commented on src/app/screens/AccountsList/styles.module.scss
> +  text-align: center;
Perfecto, corregido

2023-05-22 15:28 UTC, diazgonza17 commented on src/app/screens/AccountsList/styles.module.scss
> +  font-size: #{$large};
Funcionó, corregido

2023-05-22 15:39 UTC, diazgonza17 commented on src/app/screens/AccountsList/index.js
> +                <UTLabel>Relacion: {capitalize(account.relacion)}</UTLabel>
:+1:

2023-05-22 18:06 UTC, diazgonza17 commented on src/app/screens/AccountsList/index.js
> +    dispatch(AccountsActions.getAccounts());
Ambos errores eran a causa de no validar si ya se obtuvieron las cuentas, gracias por el aviso. Corregido

2023-05-23 22:03 UTC, facu-rodriguez requested changes
Bien! Ya casi! 

Que queden uno abajo del otro:

![Captura de pantalla de 2023-05-23 18-57-00](https://github.com/facu-rodriguez/New-training-test/assets/68086087/cbacaf06-96d5-4114-b5f4-a8d4bd0c0de9)

2023-06-02 18:02 UTC, facu-rodriguez approved these changes
Solo quedó por separarse estos botones. Considerando que estás cerrando el training y que ya es el último día lo dejo aprobado y cerrado! Buen trabajo
![Captura de pantalla de 2023-06-02 15-01-55](https://github.com/facu-rodriguez/New-training-test/assets/68086087/45566243-4261-4c9f-8719-c8478745c72c)

2023-06-02 18:02 UTC, closed without merging