TR-1-Diego::Lista de Cuentas
facu-rodriguez/New-training-test pull request #3
Opened 2023-05-18 14:32 UTC by Dieguerson

## Summary

Creada una nueva vista para listado de cuentas.

## Test Cases

Clickear las cards debería cambiar la cuenta activa y eso se debería mantener en otras vistas. Se debería poder navegar a la vista directamente, sin pasar por el dashboard y debería funcionar. La vista debería funcionar igual y mantener un estilo consistente en idinir y en segba. Solo debería cambiar el tema.

## Screenshots

![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/1a31aafd-06f6-4740-ad1e-b5a7327e9bba)
![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/9f104e25-a347-41b4-b69c-adff3ec95386)

2023-05-22 14:03 UTC, facu-rodriguez requested changes
Muy buen laburo! Unas cosas:

El botón de historial de facturas no debería haber cambiado

![Captura de pantalla de 2023-05-22 11-02-36](https://github.com/facu-rodriguez/New-training-test/assets/68086087/69eecdda-0083-46e2-934e-97bbb85f7785)


------------------------------------

2023-05-22 14:03 UTC, facu-rodriguez commented on src/app/screens/AccountsList/components/AccountCard/styles.module.scss
> +  cursor: pointer;
fijate que las props estén ordenadas alfabéticamente 
```suggestion
  background-color: unset;
  border: unset;
  cursor: pointer;
  padding: 0;
  text-align: left;
  width: 100%;
```

2023-05-22 14:03 UTC, facu-rodriguez commented on src/app/screens/AccountsList/index.js
> +    <div>
en vez de un div usemos fragment en estos casos

2023-05-22 14:04 UTC, facu-rodriguez requested changes
Muy buen laburo! Una cosa:

El botón de historial de facturas no debería haber cambiado

![Captura de pantalla de 2023-05-22 11-02-36](https://github.com/facu-rodriguez/New-training-test/assets/68086087/69eecdda-0083-46e2-934e-97bbb85f7785)

2023-05-23 19:53 UTC, Dieguerson commented on src/app/screens/AccountsList/components/AccountCard/index.js
> +        <div className={styles.owner}>{account.titular}</div>
Pasado a UTLabel!

2023-05-23 19:54 UTC, Dieguerson commented on src/app/screens/AccountsList/components/AccountCard/index.js
> +          {account.cuenta_id} - {account.relacion}
Stringed

2023-05-23 19:56 UTC, Dieguerson commented on src/app/screens/AccountsList/components/AccountCard/styles.module.scss
> +$gray: #808080;
Ya existía, no se porque lo usé así. Cualquiera. Arreglado.

2023-05-23 19:57 UTC, Dieguerson commented on src/app/screens/AccountsList/components/AccountCard/styles.module.scss
> +  cursor: pointer;
Hecho

2023-05-23 20:13 UTC, Dieguerson commented on src/app/components/Topbar/index.js
> +      <ListAltSharpIcon className={styles.icon} onClick={() => dispatch(push(ACCOUNTS_LIST))} />
Adios icono, hola botón

2023-05-23 20:13 UTC, Dieguerson commented
No se que hice para deformar ese botón, pero debería estar resuelto ahora

2023-05-23 21:54 UTC, facu-rodriguez requested changes
Ya casi! Que el botón quede del mismo tamaño que el otro! 

![Captura de pantalla de 2023-05-23 18-53-22](https://github.com/facu-rodriguez/New-training-test/assets/68086087/ece7adf7-316c-4714-9fa9-3bc08b927e1e)

2023-05-23 21:54 UTC, facu-rodriguez commented on src/app/screens/AccountsList/index.js
> +    <Fragment>
perdón, no lo ví en la corrección anterior, pero en este caso, el Fragment no haría falta porque ya tenés al UTLoading wrapeandoté todo

2023-05-24 12:35 UTC, Dieguerson commented
El alto del botón tiene una solución berreta. La única forma de hacerlo mejor que se me ocurre es pasando a grid. Si usamos grid lo armo con grid, sino estoy abierto a sugerencias.

2023-05-30 15:35 UTC, facu-rodriguez approved these changes

2023-05-30 15:35 UTC, closed without merging