feat: TR-2-Diego::Payments History, Payments Service & Actions
facu-rodriguez/New-training-test pull request #5
Opened 2023-05-19 16:51 UTC by Dieguerson

## Summary

- Service de payments
- Actions: 
  - getPayments
  - setSelectedPayment
- Reducer para payments y modificación del root reducer
- Vista de Historico de pagos
- Vista de Detalles de pago

## Test Cases

La navegación de y hacía payments debería funcionar. Payments debería ordenar la lista de pagos de más antiguo a más reciente. Clickear una fila en histórico debería llevar a detalles (`historico_de_pagos/:date`). Navegar a detalles desde la barra del navegador debería redireccionar a histórico. Salir de detalles debería disparar un dispatch que borre el pago seleccionado del estado. Todo debería funcionar en responsive y en idinir/segba

## Screenshots

![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/0c5c4cc8-2be0-4cbd-a40f-5b6d25c5df03)
![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/6b90c3f0-cc76-4fe0-adf9-8edd17864ea3)

2023-05-24 12:58 UTC, santicammarano requested changes
Muy buen trabajo 🚀 . Te dejo unos comments/sugerencias:
- Idealmente, la vista/componente Payment es accesible sólo desde PaymentsHistory, por lo que, según nuestra estructura de carpetas, debería encontrarse dentro de la misma (con su correspondiente estructura).
- Si surge un error y no mostramos la información, cómo podriamos hacer para que el usuario pueda realizar un nuevo fetch de datos? (sin necesidad de recargar la página)
<img width="708" alt="image" src="https://github.com/facu-rodriguez/New-training-test/assets/102041113/96968a58-64b2-42df-bd8a-587899c9442e">
- En los textos, utilicemos una única convención para el naming, preferentemente camelCase.
- Quedó pendiente el formateo del monto. Mas allá de eso, me gustó mucho el diseño de la card. Muy buen trabajo.
<img width="340" alt="image" src="https://github.com/facu-rodriguez/New-training-test/assets/102041113/e4daa948-e7c7-45fd-ae34-9ee1adb12968">

2023-05-24 12:58 UTC, santicammarano commented on src/app/components/Topbar/index.js
> +      <PaymentsSharpIcon className={styles.icon} onClick={() => dispatch(push(PAYMENTS_HISTORY))} />
Nice

2023-05-24 12:58 UTC, santicammarano commented on src/app/screens/PaymentsHistory/index.js
> +    <div className={styles.container}>
Podriamos pasarle estilos al `UTLoading` y evitarnos el uso del div `container`.

2023-05-24 12:58 UTC, santicammarano commented on src/config/idinir/paymentColumns.js
Esto dejemoslo definido en el archivo mismo de config. En mi opinión, no vale la pena separarlo.

2023-05-24 12:58 UTC, santicammarano commented on src/app/screens/PaymentsHistory/index.js
> +  const formattedPayments = useMemo(
- Por que useMemo? Que beneficio nos trae?
- Podriamos partir esa funcion en varias (tipo `formatDate`), y definirlas en `utils`, para poder reutilizarlas de ser necesario.

2023-05-24 12:58 UTC, santicammarano commented on src/app/screens/Payment/index.js
> +    return () => dispatch(PaymentsActions.setSelectedPayment({}));
Podríamos, a modo de buena práctica semántica, realizar una acción de `cleanCurrentPayment` para este caso.

2023-05-24 12:58 UTC, santicammarano commented on src/app/screens/Payment/index.js
> +    if (objectIsEmpty(payment)) {
Cuando sucedería este caso?

2023-05-24 12:58 UTC, santicammarano commented on src/app/screens/Payment/index.js
> +const Payment = ({ payment = {}, dispatch }) => {
```suggestion
const Payment = ({ selectedPayment = {}, dispatch }) => {
```
Por ejemplo, para aportar algo de semántica.

2023-05-29 15:11 UTC, Dieguerson commented on src/app/screens/PaymentsHistory/index.js
> +    <div className={styles.container}>
Estoy mirando el componente y los estilos que se le aplican al loading impactan solo sobre el spinner. Lo que sí puedo hacer es mandar el div para adentro y convertirlo en un child, dándole algo más de coherencia

2023-05-29 15:13 UTC, Dieguerson commented on src/config/idinir/paymentColumns.js
Movido!

2023-05-29 15:35 UTC, Dieguerson commented on src/app/screens/PaymentsHistory/index.js
> +  const formattedPayments = useMemo(
- Entiendo que useMemo debería memoizar el valor que devuelve y no volver a correr el bloque de código en su interior a menos que las dependencias cambien. En este caso no creo que cambie nada, porque no se puede seleccionar una tanda distinta de pagos o hacer algo que haga cambiar cosas que no sean los pagos dentro de la vista. La única justificación que tengo para usarlo en este caso es hacerlo future proof en caso de que se agreguen cosas a la vista. Me imagino que no va a ser el caso en el entrenamiento, pero trate de razonarlo como algo más apuntado a la vida real. Igual, sí, acá podría no estar tranquilamente.

- Hecho!

2023-05-29 15:56 UTC, Dieguerson commented on src/app/screens/Payment/index.js
> +    return () => dispatch(PaymentsActions.setSelectedPayment({}));
Hecho!

2023-05-29 15:57 UTC, Dieguerson commented on src/app/screens/Payment/index.js
> +    if (objectIsEmpty(payment)) {
En caso de una navegación manual a `/historico_de_pagos/{fecha}`

2023-05-29 15:59 UTC, Dieguerson commented on src/app/screens/Payment/index.js
> +    <div className={styles.container}>
Entiendo que es el mismo caso que para PaymentsHistory

2023-05-29 16:02 UTC, Dieguerson commented on src/app/screens/Payment/index.js
> +  paymentLoading: store.payments.paymentLoading
Voy a decir que eso quedó de algún momento que estaba probando cosas, porque no está definido ni en las props ni en prop types. Vuela

2023-05-29 16:05 UTC, Dieguerson commented on src/app/screens/Payment/index.js
> +const Payment = ({ payment = {}, dispatch }) => {
Cambiado!

2023-05-29 18:35 UTC, Dieguerson commented
- La vista ahora está dentro de PaymentsHistory
- Reload en caso de error
- Naming en camel case
- Que me faltó del formateo del monto?

2023-05-29 18:39 UTC, Dieguerson commented on src/app/screens/PaymentsHistory/index.js
> +  }, []);
Ese useEffect es más o menos una copia del de Home. Haciendo un análisis un poco más profundo entiendo que dejar el array de dependencias vacío implica que el useEffect corre solo en el primer render del componente. Siendo que lo único que dispara un re-render es el botón de reload en caso de errores, cuyo efecto es el mismo que el de el useEffect, no me parece mal dejar el array de dependencias vacío. Puedo estar pifiando en la teoría igual

2023-05-31 11:21 UTC, santicammarano commented on src/app/screens/Payment/index.js
> +    <div className={styles.container}>
Oks, no problem

2023-05-31 11:21 UTC, santicammarano commented on src/app/screens/Payment/index.js
> +    if (objectIsEmpty(payment)) {
Makes sense

2023-05-31 11:28 UTC, santicammarano commented on src/app/screens/PaymentsHistory/index.js
> +  }, []);
Con el boton de reload, tiene sentido dejarlo asi. Me parece bien 😄

2023-05-31 11:28 UTC, santicammarano commented on src/app/screens/PaymentsHistory/index.js
> +  const formattedPayments = useMemo(
Genial Diego!

2023-05-31 11:28 UTC, santicammarano commented
> * La vista ahora está dentro de PaymentsHistory
> * Reload en caso de error
> * Naming en camel case
> * Que me faltó del formateo del monto?

Del mont faltaba el $ que agregaste!

2023-05-31 11:31 UTC, santicammarano requested changes
- Creo que falto cambiar las translations en el archivo donde se usan
![image](https://github.com/facu-rodriguez/New-training-test/assets/102041113/65c3150d-84e2-49de-8159-7108fc1d61cd)
- Recorda que, para mantener la estructura de carpetas, es necesario que el componente Payment vaya dentro de la carpeta `components` correspondiente a `PaymentsHistory`
![image](https://github.com/facu-rodriguez/New-training-test/assets/102041113/dcb23541-26fc-4ca7-9ac6-84185d19f12d)

2023-05-31 11:33 UTC, santicammarano commented on src/app/screens/PaymentsHistory/index.js
> +              {' '}
```suggestion
```

2023-05-31 15:10 UTC, Dieguerson commented
> * Creo que falto cambiar las translations en el archivo donde se usan
>   ![image](https://user-images.githubusercontent.com/102041113/242258830-65c3150d-84e2-49de-8159-7108fc1d61cd.png)
> * Recorda que, para mantener la estructura de carpetas, es necesario que el componente Payment vaya dentro de la carpeta `components` correspondiente a `PaymentsHistory`
>   ![image](https://user-images.githubusercontent.com/102041113/242259107-dcb23541-26fc-4ca7-9ac6-84185d19f12d.png)

Modificado!

2023-05-31 15:10 UTC, Dieguerson commented on src/app/screens/PaymentsHistory/index.js
> +              {' '}
Voló

2023-06-13 17:27 UTC, closed without merging