Tr 2 lucas zorzin
facu-rodriguez/New-training-test pull request #6
Opened 2023-05-19 18:12 UTC by LucasZorzin

## Summary

[Change!] Describe your feature, problems you had, notes, improvements and others.

## Test Cases

[Change!] Add test cases or useful information for reviewers to test and check pull request changes.

## Screenshots

[Change!] Show the screenshots of the views you modified.

## Jira Card

[Change!] Link to the associated Jira card.

2023-05-22 14:26 UTC, santicammarano commented on src/app/screens/Home/index.js
> +import { BILLS_HISTORY, LIST_OF_PAYMENTS } from 'constants/routes';
```suggestion
import { BILLS_HISTORY, PAYMENTS_HISTORY } from 'constants/routes';
```
Para continuar con la nomenclatura utilizada.

2023-05-22 15:39 UTC, santicammarano requested changes
Muy buen trabajo! Te dejo unos comments
- Recordar que la funcionalidad pedida era el historio de pagos, **no** el histórico de las facturas pagadas.
- `PaymentDetail` es un componente propio de `PaymentHistory`. Debería estar dentro de esta carpeta, acorde a la estructura que utilizamos. Also, en mi opinión, y a modo de comentario muy pequeño, `PaymentsHistory` sería un mejor suit para el nombre de la screen.
- En la mayor parte de los casos, para mostrar textos utilizamos el componente `UTLabel`, antes que un `span` o un `h1`, por ejemplo. Revisar el uso de los mismos.

2023-05-22 15:39 UTC, santicammarano commented on src/app/screens/PaymentHistory/index.js
> +  const getDate = (date, type) => {
Todas estas funciones auxiliares deben ir dentro del archivo `utils`. Luego, evaluar en qué nivel del árbol de componentes sería necesario crearlo. Por ejemplo, `formatNumber` podría ir dentro de un archivo `numberUtils`, que sería utilizado en todo el proyecto. Sin embargo, no siempre será el caso. Podemos tener utils que sean específicos de cada componente/vista a agregar.

2023-05-22 15:39 UTC, santicammarano commented on src/app/screens/PaymentHistory/constants.js
> +export const columnsIdinir = [
Para realizar esta lógica por cliente, lo mejor sería utilizar los archivos de `config` definidos en las carpetas de cada uno.

2023-05-22 15:39 UTC, santicammarano commented on src/app/screens/PaymentHistory/index.js
> +        <UTLoading loading={loading}>
Mismo comentario del UTLoading que en la pr del ejercicio 1!

2023-05-22 15:39 UTC, santicammarano commented on src/app/screens/PaymentHistory/index.js
> +  payments: store.payments.paymentHistory,
Podríamos desarrollar una función que me formatee y ordene los pagos acá, de modo que cuando los recuperemos por props ya se encuentren listos para utilizar.

2023-05-22 15:39 UTC, santicammarano commented on src/app/layout.js
> +  const onChangeRouteSetCurrentPayment = () => {
Cual es el objetivo de este código?

2023-05-23 18:20 UTC, LucasZorzin commented on src/app/layout.js
> +  const onChangeRouteSetCurrentPayment = () => {
Esto viene de la mano con la corrección de arriba, no encontraba otra forma de limpiar el estado cuando el usuario estaba fuera de la ruta especifica de un pago seleccionado.

2023-05-24 12:00 UTC, santicammarano requested changes
Buen trabajo 🚀 . Te dejo unos comentarios para seguir mejorando el codigo!
- Chequear los warnings de compilación. Muchas veces, al no estar configurado eslint no salen los mismos. No necesariamente los useEffect necesitan todas esas dependencias, pero es una buena práctica colocarlas cuando si lo hacen.
<img width="717" alt="image" src="https://github.com/facu-rodriguez/New-training-test/assets/102041113/22525b25-34f8-4638-8b48-eef0c769ed68">

- Minuscula

<img width="170" alt="image" src="https://github.com/facu-rodriguez/New-training-test/assets/102041113/419cdf7b-ec83-41bc-8f6f-f9ce2ddf89ae">

2023-05-24 13:21 UTC, LucasZorzin commented
Correcciones implementadas!

2023-05-24 16:13 UTC, santicammarano requested changes

2023-05-24 16:13 UTC, santicammarano commented on src/app/screens/PaymentsHistory/index.js
> +  payments: store.payments.payments,
Anteriormente te decía que llames a las funciones de sorting y demás así --> payments: function(store.payments.payments), por ejemplo. De esta forma, ya cuando recuperas el dato por props lo tenes listo para usarse.

2023-05-31 11:40 UTC, santicammarano commented on src/app/screens/PaymentsHistory/index.js
> +  payments: formatPaymentsUtils(store.payments.payments),
Solo a modo de comentario, el nombre de esta funcion podria ser `formatPayments`, dejando el `utils` para el nombre del archivo

2023-05-31 11:49 UTC, santicammarano approved these changes
Buen trabajo! 🚀

2023-05-31 11:50 UTC, closed without merging