feat: funcionalidad agregada -> ABM Factura Digital (idinir)
facu-rodriguez/New-training-test pull request #8
Opened 2023-05-23 13:51 UTC by LucasZorzin

## Summary

Se agregó la funcionalidad de ABM Factura Digital para el cliente idinir. Con esto, sus usuarios pueden adherirse, modificar o darse de baja a factura digital.

## Test Cases

yarn start idinir

## Screenshots

Se pedía:
![image](https://github.com/facu-rodriguez/New-training-test/assets/87238341/39d6a22c-904b-4c64-9878-359496f93254)

Resultado:
![image](https://github.com/facu-rodriguez/New-training-test/assets/87238341/54693ecf-b612-4925-9036-9ab60224c141)
![image](https://github.com/facu-rodriguez/New-training-test/assets/87238341/8faf0538-6e75-4d38-b247-65a24f88abba)
![image](https://github.com/facu-rodriguez/New-training-test/assets/87238341/ccde60c7-969f-4f75-9f92-069f3bbae289)
![image](https://github.com/facu-rodriguez/New-training-test/assets/87238341/bd14025a-1abd-4e29-9fc3-e29031ac4d59)
![image](https://github.com/facu-rodriguez/New-training-test/assets/87238341/8e95356e-ab5d-4de0-a8f4-2b22892a2a6c)

## Jira Card

[Change!] Link to the associated Jira card.

2023-05-24 11:31 UTC, facu-rodriguez requested changes
Muy buen laburo! 

Fijate que no debería recargarse la pagina: 

https://github.com/facu-rodriguez/New-training-test/assets/68086087/c633f45c-494d-4b03-832d-f822f9f22a43

-------------------------------------

Ojo con agregar cosas en una sola utility:
Esto pasa si intento levantar segba:

![Captura de pantalla de 2023-05-24 08-30-15](https://github.com/facu-rodriguez/New-training-test/assets/68086087/a50b76ec-99c8-4355-97ed-866a770b7b40)

2023-05-24 11:31 UTC, facu-rodriguez commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +// eslint-disable-next-line react/prop-types
acordate que en cada componente tenemos que tener definidas las proptypes, con lo cual, sacá esta instrucción y definite las proptypes!

2023-05-24 11:31 UTC, facu-rodriguez commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +  const dispatch = useDispatch();
cuando tenés conectado el store en el componente simplemente podés tomar el dispatch como una prop

2023-05-24 11:31 UTC, facu-rodriguez commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +          window.location.reload();
por qué estás recargando la pagina?

2023-05-24 11:31 UTC, facu-rodriguez commented on src/app/components/DigitalBill/index.js
> +  const [modal, setModal] = useState(false);
cambialo por algo mas descriptivo como: openModal o similar

2023-05-24 11:31 UTC, facu-rodriguez commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +      {show ? (
en vez de tener este show acá, movelo al padre, y que solo renderize el componente cuando el modal esté abierto!

2023-05-24 11:31 UTC, facu-rodriguez commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +    store.digitalBills.postDigitalBillsLoading,
esto puede volverse engorroso, con lo cual, lo mejor sería unificar los targets del reducer! En el mismo archivo del reducr te indico como!

2023-05-24 11:31 UTC, facu-rodriguez commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +                {type === 'modificar' || type === 'alta' ? (
en vez de tener el condicional `type === 'modificar' || type === 'alta' ? algo : null` hace directamente 

`type === 'modificar' || type === 'alta' && (algo)`

2023-05-24 11:31 UTC, facu-rodriguez commented on src/redux/digitalBills/actions.js
> +import { createTypes, completeTypes } from 'redux-recompose';
En este caso, no haría falta agregar un nuevo reducer. El de bills calza perfecto con lo que queremos ya que estamos manejando infromación de facturas! Movete las acciones al reducer de bills

2023-05-24 11:31 UTC, facu-rodriguez commented on src/redux/digitalBills/actions.js
> +    dispatch({ type: actions.PUT_DIGITAL_BILLS, target: 'putDigitalBills' });
Lo que te comentaba mas arriba de unificar los targets....

Las 3 acciones se van a ejecutar en distintos momentos y de maneras separadas y las 3 trabajan con lo mismo, factura digital, con lo cual, vos podrías pensar un único target, que sea `digitalBill` y únicamente valerte de lo que esta contenga. Entonces ya no te interesaría saber que tipo de acción del ABM está realizando, simplemente vas a buscar los valores de ditallBillLoading, digitalBillError o digitalBillMessage, y ya

2023-05-24 11:31 UTC, facu-rodriguez commented on src/app/components/DigitalBill/index.js
> +  email: array
en vez de usar el forbid prop type array, usa: arrayOf() y en este caso te quedaría:

arrayOf(string)

2023-05-24 14:30 UTC, LucasZorzin commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +          window.location.reload();
Podría hacer una acción de redux para limpiar el estado sino?

2023-05-24 15:11 UTC, LucasZorzin commented
Correcciones implementadas!

2023-05-24 15:50 UTC, LucasZorzin commented on src/app/components/CurrentAccount/Components/AccountCard/index.js
> +        {process.env.REACT_APP_UTILITY_NAME === 'idinir' && (
Es verdad, solucionado!

2023-05-24 15:51 UTC, LucasZorzin commented on src/app/components/CurrentAccount/Components/AccountCard/index.js
> +          <DigitalBill billType={adheridoFacturaDigital} email={contactEmails} />
Perfecto!

2023-05-24 15:51 UTC, LucasZorzin commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +// eslint-disable-next-line react/prop-types
Ok, perfecto!

2023-05-24 15:52 UTC, LucasZorzin commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +  const dispatch = useDispatch();
Ahh es verdad. Implementado!

2023-05-24 15:52 UTC, LucasZorzin commented on src/app/components/DigitalBill/index.js
> +  const [modal, setModal] = useState(false);
Vale

2023-05-24 15:52 UTC, LucasZorzin commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +      {show ? (
Es verdad. Implementado!

2023-05-24 15:53 UTC, LucasZorzin commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +    store.digitalBills.postDigitalBillsLoading,
Perfecto

2023-05-24 15:53 UTC, LucasZorzin commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +                {type === 'modificar' || type === 'alta' ? (
Joya, es verdad. Lo tengo en cuenta

2023-05-24 15:53 UTC, LucasZorzin commented on src/redux/digitalBills/actions.js
> +import { createTypes, completeTypes } from 'redux-recompose';
Implementado!

2023-05-30 17:25 UTC, facu-rodriguez requested changes
Buen trabajo! Una cosa. 

Fijate que cuando cierro el modal se vuelve a dispatchear (?) el success. Eso pasa en los 3 casos y no debería ocurrir en ninguno:
![Peek 30-05-2023 14-18](https://github.com/facu-rodriguez/New-training-test/assets/68086087/b06f79a7-3a2a-4cba-9e9b-6b89ad67b704)

2023-05-30 17:25 UTC, facu-rodriguez commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +      case 'baja':
extraé "baja", "alta" y "modificar" a un archivo de constants dentro de la carpeta constants.js en el root del proyecto y utilizalas en todos los casos donde la necesites.

Te debería quedar algo así:

export const DELETE_METHOD: 'baja';

y entonces en este caso deberías importarte esa constante acá y usarla así: 
```suggestion
      case : DELETE_METHOD:
```

2023-05-30 17:25 UTC, facu-rodriguez commented on src/app/components/DigitalBill/index.js
> +            <UTButton colorTheme="success" onClick={() => handleModal('modificar')}>
usá las constantes que creaste que te marqué en el punto de arriba

2023-05-31 19:47 UTC, LucasZorzin commented
> Buen trabajo! Una cosa.
> 
> Fijate que cuando cierro el modal se vuelve a dispatchear (?) el success. Eso pasa en los 3 casos y no debería ocurrir en ninguno: ![Peek 30-05-2023 14-18](https://user-images.githubusercontent.com/68086087/242044546-b06f79a7-3a2a-4cba-9e9b-6b89ad67b704.gif)


Debería 'dispatchearse' solo un DELETE_DIGITAL_BILLS?

2023-06-02 17:55 UTC, LucasZorzin commented on src/app/components/DigitalBill/Components/DigitalBillModal/index.js
> +      case 'baja':
Perfecto, realizado!

2023-06-02 17:56 UTC, LucasZorzin commented on src/app/components/DigitalBill/index.js
> +            <UTButton colorTheme="success" onClick={() => handleModal('modificar')}>
Ok!

2023-06-02 21:05 UTC, LucasZorzin commented
Correcciones implementadas!

2023-06-06 12:15 UTC, facu-rodriguez approved these changes

2023-06-06 12:15 UTC, closed without merging