feat: TR-3-Diego::ABM factura digital y card con detalle
facu-rodriguez/New-training-test pull request #9
Opened 2023-05-23 19:42 UTC by Dieguerson

## Summary

- Card para mostrar detalle de factura digital
- Modal genérico para ABM factura digital
- Estados para ese modal dependiendo del trámite
- Acciones, reducer y service para ABM

## Test Cases

La card de factura digital debería cambiar según si el cliente está o no adherido. Los distintos botones dentro de la card deberían abrir distintos estados del modal. Los estados del modal que usen input no deberían permitir continuar si el texto ingresado es inválido. El botón de cancel debería cerrar el botón. Se debería poder realizar el ABM sin problemas. Todo debería ajustarse a distintos tamaños de pantalla. Iniciar el proyecto en segba debería ser posible, pero no se debería mostrar nada del nuevo feat.

## Screenshots

![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/aed8ee4c-0a94-40c5-9b5e-f3531fbe3c44)
![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/8f090056-9b4d-4969-b946-c57cb464529f)
![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/252e3a62-37d1-40b5-b846-0941a5a94bb4)
![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/0ac97780-e850-45a1-8ba5-fa5e9ed4dc72)
![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/d14d0a2e-529c-4f4a-8fd5-3c4fa3e269b5)
![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/8fac0d96-d543-45b7-8a4e-fa361da561e9)
![image](https://github.com/facu-rodriguez/New-training-test/assets/72291544/788ef821-9bb7-4d10-b15e-9068dfa8968e)

2023-05-24 12:13 UTC, facu-rodriguez requested changes
Buen laburo :muscle:

Agregá un feedback visual que indique por qué no estoy pudiendo aceptar y enviar la adhesión:

https://github.com/facu-rodriguez/New-training-test/assets/68086087/b39cad09-bbc7-4bc7-a7d7-de920e6493a7

1 de 2. El botón de aceptar está siempre habilitado al inicio y si intenta submitear y es un mail invalido, se pone disabled y le avisa al usuario que el email es invalido.
2 de 2, dejar el botón deshabilitado y agregar el mensaje siempre que el email sea invaido

--------------------------------------------

- agregate un loading y deshabilita los botones cuando este sea verdadero para prevenir estos casos:


https://github.com/facu-rodriguez/New-training-test/assets/68086087/aa2dc2b0-3470-4fbb-82e7-b41e8695e775

2023-05-24 12:13 UTC, facu-rodriguez commented on src/redux/accounts/reducer.js
> +  primaryActions: [actions.GET_ACCOUNTS, actions.DIGITAL_BILLING_UPDATE],
faltan las otras dos 
`DIGITAL_BILLING_SUBSCRIPTION, DIGITAL_BILLING_UNSUBSCRIPTION`

2023-05-24 12:13 UTC, facu-rodriguez commented on src/config/segba/texts.js
> +      digitalBilling: 'Facturación digital',
same que idinir

2023-05-24 12:13 UTC, facu-rodriguez commented on src/redux/accounts/actions.js
> +      const accounts = await AccountService.getAccounts();
lo mismo que arriba

2023-05-24 12:13 UTC, facu-rodriguez commented on src/redux/accounts/actions.js
> +    dispatch({ type: actions.DIGITAL_BILLING_UNSUBSCRIPTION, target: 'accountsZ' });
el target debería ser el mismo para las 3 acciones ya que todo trabaj sobre factura digital. En este caso nunca se van a ejecutar dos de estas acciones en simultaneo con lo cual no debería traerte problemas

2023-05-24 12:13 UTC, facu-rodriguez commented on src/redux/accounts/actions.js
> +    dispatch({ type: actions.DIGITAL_BILLING_SUBSCRIPTION, target: 'accounts' });
Acá lo mismo, más allá de lo que te marqué arriba de que deberían tener el mismo target, el target no sería el de accounts ya que en el de accounts guardamos las cuentas que recuperamos.

2023-05-24 13:12 UTC, Dieguerson commented on src/config/idinir/texts.js
> +      digitalBilling: 'Facturación digital',
Cambiado!

2023-05-24 16:14 UTC, Dieguerson commented on src/redux/accounts/reducer.js
> +  primaryActions: [actions.GET_ACCOUNTS, actions.DIGITAL_BILLING_UPDATE],
Todo esto se fue a vivir a Bills

2023-05-24 16:15 UTC, Dieguerson commented on src/redux/accounts/actions.js
> +      const accounts = await AccountService.getAccounts();
A Bills et al.

2023-05-24 16:16 UTC, Dieguerson commented on src/redux/accounts/actions.js
> +        contact_emails: [...newCurrent.contact_emails, email]
Cambiado

2023-05-24 16:16 UTC, Dieguerson commented on src/redux/accounts/actions.js
> +    dispatch({ type: actions.DIGITAL_BILLING_UNSUBSCRIPTION, target: 'accountsZ' });
Cambiados los targets

2023-05-24 16:16 UTC, Dieguerson commented on src/redux/accounts/actions.js
> +    dispatch({ type: actions.DIGITAL_BILLING_SUBSCRIPTION, target: 'accounts' });
Acá también

2023-05-24 16:21 UTC, Dieguerson commented
Agregado loading a la card de factura digital

2023-05-29 13:29 UTC, Dieguerson commented
Agregada etiqueta de validación cuando el email es incorrecto y loading que no permite al usuario clickear botones mientras se está procesando una acción

2023-05-29 14:50 UTC, Dieguerson commented
Agrego mejora que me pidió Guido en el componente de DigitalBilling

2023-05-31 13:20 UTC, facu-rodriguez commented on src/app/screens/Home/constants.js
> +    ctaText: i18.t('digitalBills:modal.accept'),
estos 2 textos se repiten en los 3 casos, con lo cual, podrías directamente pasarselos al modal, sin tener que discriminar según el tipo de acción a realizar, sino te queda 3 veces repetido el mismo código!

2023-05-31 13:23 UTC, facu-rodriguez commented on src/app/screens/Home/index.js
> +  const [modalStatus, setModalStatus] = useState(modalState.closed);
acá directamente manejá si mostrar o no el modal con esto, en vez de modificar el modalState. De hecho, con los cambios que te pedí, ya no va a quedar como un estado, sino que va a ser más bien un diccionario que indica que mostrar según el tipo de acción, con lo cual, si querés actualizarle el nombre no estaría mal!

2023-05-31 13:24 UTC, facu-rodriguez commented on src/app/screens/Home/index.js
> +  };
```suggestion
  const handleCta = action => {
    if (action === 'modify') dispatch(BillsActions.digitalBillingUpdate(inputValue));
    if (action === 'subscribe') dispatch(BillsActions.digitalBillingSubscription(inputValue));
    if (action === 'unsubscribe') dispatch(BillsActions.digitalBillingUnsubscription(inputValue));
    setModalStatus(modalState.closed);
  };
```
O bien podría ser un switch también!

2023-05-31 15:29 UTC, Dieguerson commented on src/app/screens/Home/constants.js
> +    showModal: false
Hecho. Creo...

2023-05-31 15:32 UTC, Dieguerson commented on src/app/screens/Home/index.js
> +  const [modalStatus, setModalStatus] = useState(modalState.closed);
En teoría está hecho. No estoy seguro de entender el cambio que me pedís, así que tal vez después tal vez lo podemos charlar si lo que hice no es a lo que apuntabas

2023-06-02 18:11 UTC, facu-rodriguez approved these changes
muy buen labiuro! :muscle:

2023-06-02 18:11 UTC, closed without merging